/*
 * Seed data for The Sims Build Randomizer lot traits, ordered by name
 */
insert into
  sims4.lot_traits_br (lot_trait_name, phrase)
values
  ('Bracing Breezes',         'with the lot trait ❛Bracing Breezes❜'        ),
  ('Breeding Grounds',        'with the lot trait ❛Breeding Grounds❜'       ),
  ('Cat Hangout',             'with the lot trait ❛Cat Hangout❜'            ),
  ('Celebrity Home',          'with the lot trait ❛Celebrity Home❜'         ),
  ('Chef''s Kitchen',         'with the lot trait ❛Chef''s Kitchen❜'        ),
  ('Child''s Play',           'with the lot trait ❛Child''s Play❜'          ),
  ('Convivial',               'with the lot trait ❛Convivial❜'              ),
  ('Dog Hangout',             'with the lot trait ❛Dog Hangout❜'            ),
  ('Eco Lot',                 'with the lot trait ❛Eco Lot❜'                ),
  ('Fairy Passage',           'with the lot trait ❛Fairy Passage❜'          ),
  ('Fast Internet',           'with the lot trait ❛Fast internet❜'          ),
  ('Geothermal',              'with the lot trait ❛Geothermal❜'             ),
  ('Gnomes',                  'with the lot trait ❛Gnomes❜'                 ),
  ('Good Schools',            'with the lot trait ❛Good Schools❜'           ),
  ('Great Acoustics',         'with the lot trait ❛Great Acoustics❜'        ),
  ('Great Soil',              'with the lot trait ❛Great Soil❜'             ),
  ('Home Studio',             'with the lot trait ❛Home Studio❜'            ),
  ('Homey',                   'with the lot trait ❛Homey❜'                  ),
  ('Island Spirits',          'with the lot trait ❛Island Spirits❜'         ),
  ('Mean Vibe',               'with the lot trait ❛Mean Vibe❜'              ),
  ('Natural Light',           'with the lot trait ❛Natural Light❜'          ),
  ('Natural Well',            'with the lot trait ❛Natural Well❜'           ),
  ('On A Dark Ley Line',      'with the lot trait ❛On A Dark Ley Line❜'     ),
  ('On Hallowed Grounds',     'with the lot trait ❛On Hallowed Grounds❜'    ),
  ('On Ley Line',             'with the lot trait ❛On Ley Line❜'            ),
  ('Party Place',             'with the lot trait ❛Part Place❜'             ),
  ('Peace and Quiet',         'with the lot trait ❛Peace and Quiet❜'        ),
  ('Penny Pixies',            'with the lot trait ❛Penny Pixies❜'           ),
  ('Private Dwelling',        'with the lot trait ❛Private Dwelling❜'       ),
  ('Registered Vampire Lair', 'with the lot trait ❛Registered Vampire Lair❜'),
  ('Romantic Aura',           'with the lot trait ❛Romantic Aura❜'          ),
  ('Science Lair',            'with the lot trait ❛Science Lair❜'           ),
  ('Singles Hangout',         'with the lot trait ❛Singles Hangout❜'        ),
  ('Study Spot',              'with the lot trait ❛Study Spot❜'             ),
  ('Sunny Aspect',            'with the lot trait ❛Sunny Aspect❜'           ),
  ('Teen Neighborhood',       'with the lot trait ❛Teen Neighborhood❜'      ),
  ('Training Ground',         'with the lot trait ❛Training Ground❜'        ),
  ('Vampire Nexus',           'with the lot trait ❛Vampire Nexus❜'          );