/*
 * Seed data for The Sims Build Randomizer architectures, ordered by architecture_name
 */
insert into
  sims4.architectures_br (pack_code, architecture_name, phrase)
values
  ('BASE', 'A-Frame House',              'an A-Frame House'            ),
  ('BASE', 'Adobe House',                'an Adobe House'              ),
  ('BASE', 'Apartment',                  'an Apartment'                ),
  ('BASE', 'Art Deco House',             'an Art Deco House'           ),
  ('BASE', 'Beach House',                'a Beach House'               ),
  ('BASE', 'British Farmhouse',          'a British Farmhouse'         ),
  ('BASE', 'Cape Cod Bungalow',          'a Cape Cod Bungalow'         ),
  ('BASE', 'Castle',                     'a Castle'                    ),
  ('BASE', 'Colonial House',             'a Colonial House'            ),
  ('BASE', 'Cottage',                    'a Cottage'                   ),
  ('BASE', 'Craftsman House',            'a Craftsman House'           ),
  ('BASE', 'Duplex',                     'a Duplex'                    ),
  ('BASE', 'Dutch Colonial House',       'a Dutch Colonial House'      ),
  ('EP09', 'Eco Friendly House',         'an Eco Friendly House'       ),
  ('BASE', 'Glass House',                'an All Glass House'          ),
  ('BASE', 'Gothic Victorian House',     'a Gothic Victorian House'    ),
  ('SP18', 'Haunted House',              'a Haunted House'             ),
  ('BASE', 'Italianate House',           'an Italianate House'         ),
  ('BASE', 'Lighthouse',                 'a Lighthouse'                ),
  ('BASE', 'Log Cabin',                  'a Log Cabin'                 ),
  ('BASE', 'Mansion',                    'a Mansion'                   ),
  ('BASE', 'Mediterranean House',        'a Mediterranean House'       ),
  ('BASE', 'Micro House',                'a Micro 32-tile House'       ),
  ('BASE', 'Mid-century Modern House',   'a Mid-century Modern House'  ),
  ('BASE', 'Modern Farmhouse',           'a Modern Farmhouse'          ),
  ('BASE', 'Modern House',               'a Modern House'              ),
  ('BASE', 'Moroccan Riad',              'a Moroccan Riad'             ),
  ('BASE', 'Penthouse',                  'a Penthouse'                 ),
  ('BASE', 'Ranch Bungalow',             'a Ranch Bungalow'            ),
  ('BASE', 'Rental House',               'a Rental House'              ),
  ('BASE', 'Rustic Country House',       'a Rustic Country House'      ),
  ('BASE', 'Secret Hideout',             'a Secret Hideout'            ),
  ('BASE', 'Shack',                      'a Shack'                     ),
  ('BASE', 'Shipping Container House',   'a Shipping Container House'  ),
  ('BASE', 'Small House',                'a Small 100-tile House'      ),
  ('BASE', 'Suburban House',             'a Suburban House'            ),
  ('BASE', 'Suburban Townhouse',         'a Suburban Townhouse'        ),
  ('BASE', 'Tiny House',                 'a Tiny 64-tile House'        ),
  ('EP10', 'Traditional Japanese House', 'a Traditional Japanese House'),
  ('BASE', 'Trailer',                    'a Trailer or Trailer Park'   ),
  ('BASE', 'Treehouse',                  'a Treehouse'                 ),
  ('BASE', 'Tudor House',                'a Tudor House'               ),
  ('BASE', 'Underground Bunker',         'an Underground Bunker'       ),
  ('BASE', 'Victorian House',            'a Victorian House'           ),
  ('BASE', 'Victorian Row House',        'a Victorian Row House'       );