/*
 * Seed data for The Sims 4 lot traits, ordered by name
 */
insert into
  sims4.lot_traits (pack_code, name)
values
  ('BASE', 'Bracing Breezes'        ),
  ('EP04', 'Breeding Grounds'       ),
  ('EP04', 'Cat Hangout'            ),
  ('EP06', 'Celebrity Home'         ),
  ('EP03', 'Chef''s Kitchen'        ),
  ('EP03', 'Child''s Play'          ),
  ('BASE', 'Convivial'              ),
  ('EP04', 'Dog Hangout'            ),
  ('EP09', 'Eco Lot'                ),
  ('EP19', 'Fairy Passage'          ),
  ('BASE', 'Fast Internet'          ),
  ('EP09', 'Geothermal'             ),
  ('EP03', 'Gnomes'                 ),
  ('EP03', 'Good Schools'           ),
  ('BASE', 'Great Acoustics'        ),
  ('EP03', 'Great Soil'             ),
  ('EP03', 'Home Studio'            ),
  ('BASE', 'Homey'                  ),
  ('EP07', 'Island Spirits'         ),
  ('EP03', 'Mean Vibe'              ),
  ('BASE', 'Natural Light'          ),
  ('EP09', 'Natural Well'           ),
  ('GP04', 'On A Dark Ley Line'     ),
  ('EP17', 'On Hallowed Grounds'    ),
  ('EP03', 'On Ley Line'            ),
  ('EP03', 'Party Place'            ),
  ('GP06', 'Peace and Quiet'        ),
  ('EP03', 'Penny Pixies'           ),
  ('BASE', 'Private Dwelling'       ),
  ('GP04', 'Registered Vampire Lair'),
  ('EP03', 'Romantic Aura'          ),
  ('BASE', 'Science Lair'           ),
  ('EP16', 'Singles Hangout'        ),
  ('EP08', 'Study Spot'             ),
  ('EP03', 'Sunny Aspect'           ),
  ('BASE', 'Teen Neighborhood'      ),
  ('EP04', 'Training Ground'        ),
  ('GP04', 'Vampire Nexus'          );