/*
 * Seed data for The Sims Build Randomizer specials, ordered by phrase
 */
insert into
  sims4.specials_br (pack_code, type, phrase)
values
  ('GP09', 'Object', '3 Star Wars Objects'                      ),
  ('EP11', 'Object', 'Animal Shed'                              ),
  ('SP46', 'Object', 'Anywhere Any Fare Food Stand'             ),
  ('EP19', 'Object', 'Apothecary Table'                         ),
  ('EP02', 'Object', 'Arcade Machine'                           ),
  ('EP20', 'Object', 'Archery Target'                           ),
  ('BASE', 'Room',   'Art Studio or Gallery'                    ),
  ('BASE', 'Room',   'Attic'                                    ),
  ('GP11', 'Object', 'Backyard Wedding Area'                    ),
  ('SP12', 'Object', 'Ball Pit'                                 ),
  ('SP01', 'Object', 'Banquet Table'                            ),
  ('BASE', 'Object', 'Bar'                                      ),
  ('BASE', 'Room',   'Basement'                                 ),
  ('EP03', 'Object', 'Basketball Court'                         ),
  ('EP05', 'Object', 'Bee Farm'                                 ),
  ('EP13', 'Object', 'BFF Super-Duper Friendship Kit'           ),
  ('EP20', 'Object', 'Blender'                                  ),
  ('SP10', 'Object', 'Bowling Alley'                            ),
  ('EP03', 'Object', 'Bubble Blower Machine'                    ),
  ('SP09', 'Room',   'Butler''s Bedroom'                        ),
  ('EP20', 'Object', 'Butterfly & Moth Habitat'                 ),
  ('GP08', 'Room',   'Cauldron Room'                            ),
  ('BASE', 'Room',   'Cemetary or Mausoleum'                    ),
  ('EP12', 'Object', 'Cheer Mat'                                ),
  ('GP03', 'Object', 'Chef Station'                             ),
  ('EP11', 'Object', 'Chicken Coop'                             ),
  ('BASE', 'Object', 'Coffee or Tea Machine'                    ),
  ('EP16', 'Object', 'Costume Trunk'                            ),
  ('BASE', 'Room',   'Craft Room'                               ),
  ('EP17', 'Object', 'Crypt of Eternity'                        ),
  ('BASE', 'Object', 'Cupcake Machine'                          ),
  ('SP04', 'Object', 'Decorate for Halloween'                   ),
  ('FP01', 'Object', 'Decorate for Winterfest'                  ),
  ('BASE', 'Room',   'DJ or Music Room'                         ),
  ('EP09', 'Object', 'Dumpster'                                 ),
  ('EP15', 'Object', 'Electrical Fuse Box'                      ),
  ('EP19', 'Object', 'Fairy Home'                               ),
  ('GP05', 'Object', 'Family Bulletin Board'                    ),
  ('GP10', 'Object', 'Fantastical Play Tent'                    ),
  ('BASE', 'Object', 'Fire Pit or Bonfire'                      ),
  ('EP20', 'Object', 'Flutterarium Caterpillar Incubator'       ),
  ('BASE', 'Object', 'Food & Flower Garden'                     ),
  ('BASE', 'Object', 'Fountain'                                 ),
  ('SP01', 'Object', 'Fountain of Mirth'                        ),
  ('EP20', 'Object', 'Free Weights'                             ),
  ('BASE', 'Object', 'Fruit Trees'                              ),
  ('BASE', 'Room',   'Game Room'                                ),
  ('BASE', 'Room',   'Garage or Workshop'                       ),
  ('BASE', 'Room',   'Garden Shed'                              ),
  ('SP49', 'Object', 'Gemology Table'                           ),
  ('EP18', 'Object', 'Grammy''s Family Recipes'                 ),
  ('BASE', 'Room',   'Greenhouse'                               ),
  ('EP17', 'Object', 'Grim Standard Ascendant Crow'             ),
  ('BASE', 'Room',   'Guest Bedroom'                            ),
  ('EP18', 'Room',   'Home Business'                            ),
  ('BASE', 'Room',   'Home Gym'                                 ),
  ('BASE', 'Room',   'Home Theatre'                             ),
  ('EP15', 'Object', 'Hopscotch'                                ),
  ('EP14', 'Object', 'Horse Stuff'                              ),
  ('BASE', 'Object', 'Hot Tub'                                  ),
  ('BASE', 'Object', 'Huge Food Farm'                           ),
  ('SP03', 'Object', 'Ice Cream Machine'                        ),
  ('EP20', 'Object', 'ImagineMe! Doll'                          ),
  ('EP09', 'Object', 'Insect Farm'                              ),
  ('EP03', 'Object', 'Karaoke Machine'                          ),
  ('EP18', 'Object', 'Kate & Berry Sweet Treats Fabricator 3000'),
  ('EP20', 'Object', 'Kayak'                                    ),
  ('EP05', 'Object', 'Kiddie Pool'                              ),
  ('BASE', 'Room',   'Kids Play Room'                           ),
  ('SP17', 'Room',   'Knitting Room'                            ),
  ('EP10', 'Object', 'Kotatsu Table'                            ),
  ('EP17', 'Object', 'Lasting Legacy Family Portrait'           ),
  ('SP13', 'Room',   'Laundry Room'                             ),
  ('SP05', 'Object', 'Lilacs & Lanterns Tree'                   ),
  ('GP02', 'Room',   'Massage Room'                             ),
  ('EP17', 'Object', 'Memorial Display'                         ),
  ('EP06', 'Room',   'Money Vault'                              ),
  ('GP12', 'Object', 'Moonwood Mill Tunnel Entrance'            ),
  ('BASE', 'Object', 'Motion Gaming Rig'                        ),
  ('SP16', 'Object', 'Murphy Bed'                               ),
  ('SP49', 'Object', 'Mystical Moonlight Crystal Grid'          ),
  ('EP19', 'Object', 'Nature Press'                             ),
  ('EP14', 'Room',   'Nectar Cellar'                            ),
  ('BASE', 'Room',   'Nursery'                                  ),
  ('BASE', 'Room',   'Office'                                   ),
  ('BASE', 'Room',   'Outhouse'                                 ),
  ('EP11', 'Object', 'Oversized Garden Patch'                   ),
  ('EP20', 'Object', 'Papercrafting Kit'                        ),
  ('EP05', 'Object', 'Patchy'                                   ),
  ('BASE', 'Room',   'Patio with BBQ'                           ),
  ('SP02', 'Object', 'Perfect Patio Outdoor Living Room'        ),
  ('EP04', 'Object', 'Pet Stuff'                                ),
  ('EP01', 'Object', 'Photo Studio'                             ),
  ('SP46', 'Object', 'Pizza Oven'                               ),
  ('BASE', 'Object', 'Playground Equipment'                     ),
  ('BASE', 'Object', 'Pond'                                     ),
  ('BASE', 'Object', 'Pool'                                     ),
  ('SP05', 'Object', 'Popcorn Machine'                          ),
  ('EP18', 'Object', 'Pottery Wheel & Kiln'                     ),
  ('EP15', 'Object', 'Pressure Cooker'                          ),
  ('SP04', 'Object', 'Pumpkin Carving Station'                  ),
  ('SP07', 'Object', 'Puppet Theater'                           ),
  ('EP17', 'Object', 'Quaint Crowskin Journal'                  ),
  ('EP15', 'Room',   'Residential Rental Unit'                  ),
  ('EP08', 'Object', 'Robotics Workstation'                     ),
  ('SP12', 'Object', 'Rock Climbing Wall'                       ),
  ('BASE', 'Object', 'Rocketship'                               ),
  ('EP16', 'Object', 'Romantic Blanket'                         ),
  ('GP02', 'Room',   'Sauna'                                    ),
  ('SP18', 'Room',   'Séance Room'                              ),
  ('BASE', 'Object', 'Shrine to the Tragic Clown'               ),
  ('BASE', 'Object', 'Skylight or Glass Roof'                   ),
  ('SP08', 'Object', 'Slip n'' Slide'                           ),
  ('BASE', 'Object', 'Small Flower Garden'                      ),
  ('BASE', 'Object', 'Small Food Garden'                        ),
  ('EP20', 'Object', 'Spin Bike'                                ),
  ('EP13', 'Object', 'Splash Pad'                               ),
  ('SP46', 'Object', 'Stand Mixer'                              ),
  ('EP06', 'Object', 'Streaming Drone'                          ),
  ('BASE', 'Room',   'Sun or Plant Room'                        ),
  ('EP17', 'Object', 'Tarot Cards'                              ),
  ('EP18', 'Object', 'Tattoo Table'                             ),
  ('BASE', 'Object', 'Telescope'                                ),
  ('EP13', 'Object', 'Treehouse'                                ),
  ('GP04', 'Room',   'Vampire Coffin Room'                      ),
  ('EP16', 'Object', 'Vibromatic Nuevo Heart Bed'               ),
  ('EP06', 'Object', 'Video Station'                            ),
  ('SP07', 'Object', 'Voidcritter Battle Station'               ),
  ('SP46', 'Object', 'Waffle Maker'                             ),
  ('EP15', 'Object', 'Water Heater'                             ),
  ('EP05', 'Object', 'Weather Control Device'                   ),
  ('SP06', 'Object', 'Wishing Well'                             ),
  ('EP02', 'Object', 'Woohoo Bush'                              ),
  ('GP02', 'Room',   'Yoga Room'                                ),
  ('EP10', 'Room',   'Zen Garden'                               );