/*
 * Seed data for ref.architectures table
 */
insert into
  ref.architectures (name)
values
  ('A-Frame House'),
  ('Adobe House'),
  ('Apartment'),
  ('Art Deco House'),
  ('Beach House'),
  ('British Farmhouse'),
  ('Cape Cod Bungalow'),
  ('Castle'),
  ('Colonial House'),
  ('Cottage'),
  ('Craftsman House'),
  ('Duplex'),
  ('Dutch Colonial House'),
  ('Eco Friendly House'),
  ('Glass House'),
  ('Gothic Victorian House'),
  ('Haunted House'),
  ('Italianate House'),
  ('Lighthouse'),
  ('Log Cabin'),
  ('Mansion'),
  ('Mediterranean House'),
  ('Micro House'),
  ('Mid-century Modern House'),
  ('Modern Farmhouse'),
  ('Modern House'),
  ('Moroccan Riad'),
  ('Penthouse'),
  ('Ranch Bungalow'),
  ('Rental House'),
  ('Rustic Country House'),
  ('Secret Hideout'),
  ('Shack'),
  ('Shipping Container House'),
  ('Small House'),
  ('Suburban House'),
  ('Suburban Townhouse'),
  ('Tiny House'),
  ('Traditional Japanese House'),
  ('Trailer'),
  ('Treehouse'),
  ('Tudor House'),
  ('Underground Bunker'),
  ('Victorian House'),
  ('Victorian Row House');