/*
 * Seed data for The Sims Build Randomizer architectures, ordered by architecture_name
 */
insert into
  sims4.architectures_br (pack_code, architecture_name, phrase)
values
  ('BASE', 'A-Frame House',              'an A-Frame House'            ),
  ('BASE', 'Adobe House',                'an Adobe House'              ),
  ('BASE', 'Apartment',                  'an Apartment'                ),
  ('BASE', 'Art Deco House',             'an Art Deco House'           ),
  ('BASE', 'Beach House',                'a Beach House'               ),
  ('BASE', 'British Farmhouse',          'a British Farmhouse'         ),
  ('BASE', 'Cape Cod Bungalow',          'a Cape Cod Bungalow'         ),
  ('BASE', 'Castle',                     'a Castle'                    ),
  ('BASE', 'Colonial House',             'a Colonial House'            ),
  ('BASE', 'Cottage',                    'a Cottage'                   ),
  ('BASE', 'Craftsman House',            'a Craftsman House'           ),
  ('BASE', 'Duplex',                     'a Duplex'                    ),
  ('BASE', 'Dutch Colonial House',       'a Dutch Colonial House'      ),
  ('EP09', 'Eco Friendly House',         'an Eco Friendly House'       ),
  ('BASE', 'Glass House',                'an All Glass House'          ),
  ('BASE', 'Gothic Victorian House',     'a Gothic Victorian House'    ),
  ('SP18', 'Haunted House',              'a Haunted House'             ),
  ('BASE', 'Italianate House',           'an Italianate House'         ),
  ('BASE', 'Lighthouse',                 'a Lighthouse'                ),
  ('BASE', 'Log Cabin',                  'a Log Cabin'                 ),
  ('BASE', 'Mansion',                    'a Mansion'                   ),
  ('BASE', 'Mediterranean House',        'a Mediterranean House'       ),
  ('BASE', 'Micro House',                'a Micro 32-tile House'       ),
  ('BASE', 'Mid-century Modern House',   'a Mid-century Modern House'  ),
  ('BASE', 'Modern Farmhouse',           'a Modern Farmhouse'          ),
  ('BASE', 'Modern House',               'a Modern House'              ),
  ('BASE', 'Moroccan Riad',              'a Moroccan Riad'             ),
  ('BASE', 'Penthouse',                  'a Penthouse'                 ),
  ('BASE', 'Ranch Bungalow',             'a Ranch Bungalow'            ),
  ('BASE', 'Rental House',               'a Rental House'              ),
  ('BASE', 'Rustic Country House',       'a Rustic Country House'      ),
  ('BASE', 'Secret Hideout',             'a Secret Hideout'            ),
  ('BASE', 'Shack',                      'a Shack'                     ),
  ('BASE', 'Shipping Container House',   'a Shipping Container House'  ),
  ('BASE', 'Small House',                'a Small 100-tile House'      ),
  ('BASE', 'Suburban House',             'a Suburban House'            ),
  ('BASE', 'Suburban Townhouse',         'a Suburban Townhouse'        ),
  ('BASE', 'Tiny House',                 'a Tiny 64-tile House'        ),
  ('EP10', 'Traditional Japanese House', 'a Traditional Japanese House'),
  ('BASE', 'Trailer',                    'a Trailer or Trailer Park'   ),
  ('BASE', 'Treehouse',                  'a Treehouse'                 ),
  ('BASE', 'Tudor House',                'a Tudor House'               ),
  ('BASE', 'Underground Bunker',         'an Underground Bunker'       ),
  ('BASE', 'Victorian House',            'a Victorian House'           ),
  ('BASE', 'Victorian Row House',        'a Victorian Row House'       );

/*
 * Seed data for The Sims Build Randomizer colors, ordered by name
 */
insert into
  sims4.colors_br (color_name, phrase)
values
  ('Black',       'a Black'      ),
  ('Blue',        'a Blue'       ),
  ('Dark Brown',  'a Dark Brown' ),
  ('Gray',        'a Gray'       ),
  ('Green',       'a Green'      ),
  ('Light Brown', 'a Light Brown'),
  ('Orange',      'an Orange'    ),
  ('Pink',        'a Pink'       ),
  ('Purple',      'a Purple'     ),
  ('Rainbow',     'a Rainbow'    ),
  ('Red',         'a Red'        ),
  ('White',       'a White'      ),
  ('Yellow',      'a Yellow'     );

/*
 * Seed data for The Sims Build Randomizer lot challenges, organized by name
 */
insert into
  sims4.lot_challenges_br (lot_challenge_name, phrase)
values
  ('Creepy Crawlies',      'with the lot challenge ❛Creepy Crawlies❜'     ),
  ('Cursed',               'with the lot challenge ❛Cursed❜'              ),
  ('Filthy',               'with the lot challenge ❛Filthy❜'              ),
  ('Gremlins',             'with the lot challenge ❛Gremlins❜'            ),
  ('Grody',                'with the lot challenge ❛Grody❜'               ),
  ('Heist Havoc',          'with the lot challenge ❛Heist Havoc❜'         ),
  ('Maintenance Troubles', 'with the lot challenge ❛Maintenance Troubles❜'),
  ('Mold',                 'with the lot challenge ❛Mold❜'                ),
  ('Off-the-Grid',         'with the lot challenge ❛Off-the-Grid❜'        ),
  ('Quake Zone',           'with the lot challenge ❛Quake Zone❜'          ),
  ('Reduce and Recycle',   'with the lot challenge ❛Reduce and Recycle❜'  ),
  ('Scare Seeker',         'with the lot challenge ❛Scare Seeker❜'        ),
  ('Simple Living',        'with the lot challenge ❛Simple Living❜'       ),
  ('Spooky',               'with the lot challenge ❛Spooky❜'              ),
  ('Volcanic Activity',    'with the lot challenge ❛Volcanic Activity❜'   ),
  ('Wild Foxes',           'with the lot challenge ❛Wild Foxes❜'          ),
  ('Wild Prairie Grass',   'with the lot challenge ❛Wild Prairie Grass❜'  );

/*
 * Seed data for The Sims Build Randomizer lot traits, ordered by name
 */
insert into
  sims4.lot_traits_br (lot_trait_name, phrase)
values
  ('Bracing Breezes',         'with the lot trait ❛Bracing Breezes❜'        ),
  ('Breeding Grounds',        'with the lot trait ❛Breeding Grounds❜'       ),
  ('Cat Hangout',             'with the lot trait ❛Cat Hangout❜'            ),
  ('Celebrity Home',          'with the lot trait ❛Celebrity Home❜'         ),
  ('Chef''s Kitchen',         'with the lot trait ❛Chef''s Kitchen❜'        ),
  ('Child''s Play',           'with the lot trait ❛Child''s Play❜'          ),
  ('Convivial',               'with the lot trait ❛Convivial❜'              ),
  ('Dog Hangout',             'with the lot trait ❛Dog Hangout❜'            ),
  ('Eco Lot',                 'with the lot trait ❛Eco Lot❜'                ),
  ('Fairy Passage',           'with the lot trait ❛Fairy Passage❜'          ),
  ('Fast Internet',           'with the lot trait ❛Fast internet❜'          ),
  ('Geothermal',              'with the lot trait ❛Geothermal❜'             ),
  ('Gnomes',                  'with the lot trait ❛Gnomes❜'                 ),
  ('Good Schools',            'with the lot trait ❛Good Schools❜'           ),
  ('Great Acoustics',         'with the lot trait ❛Great Acoustics❜'        ),
  ('Great Soil',              'with the lot trait ❛Great Soil❜'             ),
  ('Home Studio',             'with the lot trait ❛Home Studio❜'            ),
  ('Homey',                   'with the lot trait ❛Homey❜'                  ),
  ('Island Spirits',          'with the lot trait ❛Island Spirits❜'         ),
  ('Mean Vibe',               'with the lot trait ❛Mean Vibe❜'              ),
  ('Natural Light',           'with the lot trait ❛Natural Light❜'          ),
  ('Natural Well',            'with the lot trait ❛Natural Well❜'           ),
  ('On A Dark Ley Line',      'with the lot trait ❛On A Dark Ley Line❜'     ),
  ('On Hallowed Grounds',     'with the lot trait ❛On Hallowed Grounds❜'    ),
  ('On Ley Line',             'with the lot trait ❛On Ley Line❜'            ),
  ('Party Place',             'with the lot trait ❛Part Place❜'             ),
  ('Peace and Quiet',         'with the lot trait ❛Peace and Quiet❜'        ),
  ('Penny Pixies',            'with the lot trait ❛Penny Pixies❜'           ),
  ('Private Dwelling',        'with the lot trait ❛Private Dwelling❜'       ),
  ('Registered Vampire Lair', 'with the lot trait ❛Registered Vampire Lair❜'),
  ('Romantic Aura',           'with the lot trait ❛Romantic Aura❜'          ),
  ('Science Lair',            'with the lot trait ❛Science Lair❜'           ),
  ('Singles Hangout',         'with the lot trait ❛Singles Hangout❜'        ),
  ('Study Spot',              'with the lot trait ❛Study Spot❜'             ),
  ('Sunny Aspect',            'with the lot trait ❛Sunny Aspect❜'           ),
  ('Teen Neighborhood',       'with the lot trait ❛Teen Neighborhood❜'      ),
  ('Training Ground',         'with the lot trait ❛Training Ground❜'        ),
  ('Vampire Nexus',           'with the lot trait ❛Vampire Nexus❜'          );

/*
 * Seed data for The Sims Build Randomizer specials, ordered by phrase
 */
insert into
  sims4.specials_br (pack_code, type, phrase)
values
  ('GP09', 'Object', '3 Star Wars Objects'                      ),
  ('EP11', 'Object', 'Animal Shed'                              ),
  ('SP46', 'Object', 'Anywhere Any Fare Food Stand'             ),
  ('EP19', 'Object', 'Apothecary Table'                         ),
  ('EP02', 'Object', 'Arcade Machine'                           ),
  ('EP20', 'Object', 'Archery Target'                           ),
  ('BASE', 'Room',   'Art Studio or Gallery'                    ),
  ('BASE', 'Room',   'Attic'                                    ),
  ('GP11', 'Object', 'Backyard Wedding Area'                    ),
  ('SP12', 'Object', 'Ball Pit'                                 ),
  ('SP01', 'Object', 'Banquet Table'                            ),
  ('BASE', 'Object', 'Bar'                                      ),
  ('BASE', 'Room',   'Basement'                                 ),
  ('EP03', 'Object', 'Basketball Court'                         ),
  ('EP05', 'Object', 'Bee Farm'                                 ),
  ('EP13', 'Object', 'BFF Super-Duper Friendship Kit'           ),
  ('EP20', 'Object', 'Blender'                                  ),
  ('SP10', 'Object', 'Bowling Alley'                            ),
  ('EP03', 'Object', 'Bubble Blower Machine'                    ),
  ('SP09', 'Room',   'Butler''s Bedroom'                        ),
  ('EP20', 'Object', 'Butterfly & Moth Habitat'                 ),
  ('GP08', 'Room',   'Cauldron Room'                            ),
  ('BASE', 'Room',   'Cemetary or Mausoleum'                    ),
  ('EP12', 'Object', 'Cheer Mat'                                ),
  ('GP03', 'Object', 'Chef Station'                             ),
  ('EP11', 'Object', 'Chicken Coop'                             ),
  ('BASE', 'Object', 'Coffee or Tea Machine'                    ),
  ('EP16', 'Object', 'Costume Trunk'                            ),
  ('BASE', 'Room',   'Craft Room'                               ),
  ('EP17', 'Object', 'Crypt of Eternity'                        ),
  ('BASE', 'Object', 'Cupcake Machine'                          ),
  ('SP04', 'Object', 'Decorate for Halloween'                   ),
  ('FP01', 'Object', 'Decorate for Winterfest'                  ),
  ('BASE', 'Room',   'DJ or Music Room'                         ),
  ('EP09', 'Object', 'Dumpster'                                 ),
  ('EP15', 'Object', 'Electrical Fuse Box'                      ),
  ('EP19', 'Object', 'Fairy Home'                               ),
  ('GP05', 'Object', 'Family Bulletin Board'                    ),
  ('GP10', 'Object', 'Fantastical Play Tent'                    ),
  ('BASE', 'Object', 'Fire Pit or Bonfire'                      ),
  ('EP20', 'Object', 'Flutterarium Caterpillar Incubator'       ),
  ('BASE', 'Object', 'Food & Flower Garden'                     ),
  ('BASE', 'Object', 'Fountain'                                 ),
  ('SP01', 'Object', 'Fountain of Mirth'                        ),
  ('EP20', 'Object', 'Free Weights'                             ),
  ('BASE', 'Object', 'Fruit Trees'                              ),
  ('BASE', 'Room',   'Game Room'                                ),
  ('BASE', 'Room',   'Garage or Workshop'                       ),
  ('BASE', 'Room',   'Garden Shed'                              ),
  ('SP49', 'Object', 'Gemology Table'                           ),
  ('EP18', 'Object', 'Grammy''s Family Recipes'                 ),
  ('BASE', 'Room',   'Greenhouse'                               ),
  ('EP17', 'Object', 'Grim Standard Ascendant Crow'             ),
  ('BASE', 'Room',   'Guest Bedroom'                            ),
  ('EP18', 'Room',   'Home Business'                            ),
  ('BASE', 'Room',   'Home Gym'                                 ),
  ('BASE', 'Room',   'Home Theatre'                             ),
  ('EP15', 'Object', 'Hopscotch'                                ),
  ('EP14', 'Object', 'Horse Stuff'                              ),
  ('BASE', 'Object', 'Hot Tub'                                  ),
  ('BASE', 'Object', 'Huge Food Farm'                           ),
  ('SP03', 'Object', 'Ice Cream Machine'                        ),
  ('EP20', 'Object', 'ImagineMe! Doll'                          ),
  ('EP09', 'Object', 'Insect Farm'                              ),
  ('EP03', 'Object', 'Karaoke Machine'                          ),
  ('EP18', 'Object', 'Kate & Berry Sweet Treats Fabricator 3000'),
  ('EP20', 'Object', 'Kayak'                                    ),
  ('EP05', 'Object', 'Kiddie Pool'                              ),
  ('BASE', 'Room',   'Kids Play Room'                           ),
  ('SP17', 'Room',   'Knitting Room'                            ),
  ('EP10', 'Object', 'Kotatsu Table'                            ),
  ('EP17', 'Object', 'Lasting Legacy Family Portrait'           ),
  ('SP13', 'Room',   'Laundry Room'                             ),
  ('SP05', 'Object', 'Lilacs & Lanterns Tree'                   ),
  ('GP02', 'Room',   'Massage Room'                             ),
  ('EP17', 'Object', 'Memorial Display'                         ),
  ('EP06', 'Room',   'Money Vault'                              ),
  ('GP12', 'Object', 'Moonwood Mill Tunnel Entrance'            ),
  ('BASE', 'Object', 'Motion Gaming Rig'                        ),
  ('SP16', 'Object', 'Murphy Bed'                               ),
  ('SP49', 'Object', 'Mystical Moonlight Crystal Grid'          ),
  ('EP19', 'Object', 'Nature Press'                             ),
  ('EP14', 'Room',   'Nectar Cellar'                            ),
  ('BASE', 'Room',   'Nursery'                                  ),
  ('BASE', 'Room',   'Office'                                   ),
  ('BASE', 'Room',   'Outhouse'                                 ),
  ('EP11', 'Object', 'Oversized Garden Patch'                   ),
  ('EP20', 'Object', 'Papercrafting Kit'                        ),
  ('EP05', 'Object', 'Patchy'                                   ),
  ('BASE', 'Room',   'Patio with BBQ'                           ),
  ('SP02', 'Object', 'Perfect Patio Outdoor Living Room'        ),
  ('EP04', 'Object', 'Pet Stuff'                                ),
  ('EP01', 'Object', 'Photo Studio'                             ),
  ('SP46', 'Object', 'Pizza Oven'                               ),
  ('BASE', 'Object', 'Playground Equipment'                     ),
  ('BASE', 'Object', 'Pond'                                     ),
  ('BASE', 'Object', 'Pool'                                     ),
  ('SP05', 'Object', 'Popcorn Machine'                          ),
  ('EP18', 'Object', 'Pottery Wheel & Kiln'                     ),
  ('EP15', 'Object', 'Pressure Cooker'                          ),
  ('SP04', 'Object', 'Pumpkin Carving Station'                  ),
  ('SP07', 'Object', 'Puppet Theater'                           ),
  ('EP17', 'Object', 'Quaint Crowskin Journal'                  ),
  ('EP15', 'Room',   'Residential Rental Unit'                  ),
  ('EP08', 'Object', 'Robotics Workstation'                     ),
  ('SP12', 'Object', 'Rock Climbing Wall'                       ),
  ('BASE', 'Object', 'Rocketship'                               ),
  ('EP16', 'Object', 'Romantic Blanket'                         ),
  ('GP02', 'Room',   'Sauna'                                    ),
  ('SP18', 'Room',   'Séance Room'                              ),
  ('BASE', 'Object', 'Shrine to the Tragic Clown'               ),
  ('BASE', 'Object', 'Skylight or Glass Roof'                   ),
  ('SP08', 'Object', 'Slip n'' Slide'                           ),
  ('BASE', 'Object', 'Small Flower Garden'                      ),
  ('BASE', 'Object', 'Small Food Garden'                        ),
  ('EP20', 'Object', 'Spin Bike'                                ),
  ('EP13', 'Object', 'Splash Pad'                               ),
  ('SP46', 'Object', 'Stand Mixer'                              ),
  ('EP06', 'Object', 'Streaming Drone'                          ),
  ('BASE', 'Room',   'Sun or Plant Room'                        ),
  ('EP17', 'Object', 'Tarot Cards'                              ),
  ('EP18', 'Object', 'Tattoo Table'                             ),
  ('BASE', 'Object', 'Telescope'                                ),
  ('EP13', 'Object', 'Treehouse'                                ),
  ('GP04', 'Room',   'Vampire Coffin Room'                      ),
  ('EP16', 'Object', 'Vibromatic Nuevo Heart Bed'               ),
  ('EP06', 'Object', 'Video Station'                            ),
  ('SP07', 'Object', 'Voidcritter Battle Station'               ),
  ('SP46', 'Object', 'Waffle Maker'                             ),
  ('EP15', 'Object', 'Water Heater'                             ),
  ('EP05', 'Object', 'Weather Control Device'                   ),
  ('SP06', 'Object', 'Wishing Well'                             ),
  ('EP02', 'Object', 'Woohoo Bush'                              ),
  ('GP02', 'Room',   'Yoga Room'                                ),
  ('EP10', 'Room',   'Zen Garden'                               );

/*
 * Seed data for The Sims Build Randomizer worlds, ordered by name
 */
insert into
  sims4.worlds_br (world_name, phrase)
values
  ('Brindleton Bay',     'in Brindleton Bay'    ),
  ('Britechester',       'in Britechester'      ),
  ('Chestnut Ridge',     'in Chestnut Ridge'    ),
  ('Ciudad Enamorada',   'in Ciudad Enamorada'  ),
  ('Copperdale',         'in Copperdale'        ),
  ('Del Sol Valley',     'in Del Sol Valley'    ),
  ('Evergreen Harbor',   'in Evergreen Harbor'  ),
  ('Forgotten Hollow',   'in Forgotten Hollow'  ),
  ('Gibbi Point',        'in Gibbi Point'       ),
  ('Glimmerbrook',       'in Glimmerbrook'      ),
  ('Granite Falls',      'in Granite Falls'     ),
  ('Henford-On-Bagley',  'in Henford On Bagley' ),
  ('Innisgreen',         'in Innisgreen'        ),
  ('Magnolia Promenade', 'in Magnolia Promenade'),
  ('Moonwood Mill',      'in Moonwood Mill'     ),
  ('Mt. Komorebi',       'in Mt Komorebi'       ),
  ('Newcrest',           'in Newcrest'          ),
  ('Nordhaven',          'in Nordhaven'         ),
  ('Oasis Springs',      'in Oasis Springs'     ),
  ('Ravenwood',          'in Ravenwood'         ),
  ('San Myshuno',        'in San Myshuno'       ),
  ('San Sequoia',        'in San Sequoia'       ),
  ('Selvadorada',        'in Selvadorada'       ),
  ('StrangerVille',      'in StrangerVille'     ),
  ('Sulani',             'in Sulani'            ),
  ('Tartosa',            'in Tartosa'           ),
  ('Tomarang',           'in Tomarang'          ),
  ('Willow Creek',       'in Willow Creek'      ),
  ('Windenburg',         'in Windenburg'        );